# Make folder backup/mysql
- name: Make folder backup/mysql
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    recurse: yes
    owner: backup
    mode: '0700'

# Create MySQL user backup
- name: Create MySQL user backup
  community.mysql.mysql_user:
    name: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_password }}"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    # '*.*': 'LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify:
    - restart mysql

# Create MySQL config for backup user
# should we use mode: 0640 for mysql_exporter config?
- name: Add MySQL backup config
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0740' 
  notify:
    - restart mysql
  register: backup_config

# Make file /etc/cron.d/mysql-backup
- name: Create file mysql-backup
  ansible.builtin.template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
  
