- name: HTTP client packages
  ansible.builtin.apt:
    name:
      - nginx-full

- name: Copy new index.html page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Start automatically with boot
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: Copy default config from local to host
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx
