
- name: Install HAproxy
  ansible.builtin.apt:
    name: haproxy

- name: Copy HAproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2       
    dest: /etc/haproxy/haproxy.cfg 
  notify: restart haproxy

- name: Install HAproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Copy HAproxy exporter config
  ansible.builtin.template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: restart haproxy exporter

#- name: Make sure haproxy is running
#  ansible.builtin.service:
#    name: haproxy
#    state: started

#- name: Make sure haproxy exporter is running
#  ansible.builtin.service:
#    name: prometheus-haproxy-exporter
#    state: started
