- name: Add an Apt singing key for Grafana
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    update_cache: yes
    name: grafana

- name: Copying Grafana template
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana

- name: Copying Dashboard preset
  ansible.builtin.copy:
    src: home.json
    dest: /usr/share/grafana/public/dashboards/home.json
  notify: restart grafana

- name: Start automatically with boot
  ansible.builtin.service:
    name: grafana-server
    enabled: yes
    state: started
  notify: change admin pass 

# change admin pass - not sure when to use.
