- name: Make user agama
  ansible.builtin.apt:
    name: 
      - uwsgi
      - uwsgi-plugin-python3
      - python3-pymysql

- name: Start automatically with boot
  ansible.builtin.service:
    name: uwsgi.service    
    enabled: yes
    state: started

- name: Copy uWSGI configuration for AGAMA application
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini  
  notify: Restart uWSGI
