{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"IrishIRL-1:9104\"}",
     "legendFormat": "IrishIRL-1"
    },
    {
     "expr": "mysql_up{instance=\"IrishIRL-2:9104\"}",
     "legendFormat": "IrishIRL-2"
    }
   ]
  },
  {
   "title": "MySQL selects per min ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  {
   "title": "MySQL server id",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"IrishIRL-1:9104\"}",
     "legendFormat": "IrishIRL-1"
    },
    {
     "expr": "mysql_global_variables_server_id{instance=\"IrishIRL-2:9104\"}",
     "legendFormat": "IrishIRL-2"
    }
   ]
  },
  {
   "title": "MySQL server read only status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"IrishIRL-1:9104\"}",
     "legendFormat": "IrishIRL-1"
    },
    {
     "expr": "mysql_global_variables_read_only{instance=\"IrishIRL-2:9104\"}",
     "legendFormat": "IrishIRL-2"
    }
   ]
  },
  {
   "title": "MySQL replication threads ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  }
 ]
}