- name: opt/agama directory
  ansible.builtin.file:
    name: /opt/agama
    state: directory

- name: Download Agama dockerfile
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Grafana Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: agama-{{ item }}
    image: agama
    published_ports: "{{ 8000 + item }}:8000"
    dns_servers: "{{ dns_servers }}"
    dns_search_domains: "{{ domain_name }}.{{ root_name }}"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  loop:
    - 1
    - 2
