- name: Install MySQL Exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
  register: prom_exporter_installed

- name: Update prometheus-mysqld-exporter to export MySQL data
  ansible.builtin.template:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart mysqld export

- name: Add MySQL exporter config
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
    - restart mysql 
    - restart mysqld export
  register: prom_exporter_installed

- name: Pause for 10 sec
  pause:
    seconds: 10
  when: prom_exporter_installed.changed

- name: Create MySQL user export
  community.mysql.mysql_user:
    name: "{{ mysql_export_user }}"
    password: "{{ mysql_export_password }}"
    priv:
      '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify: 
    - restart mysql
    - restart mysqld export

