- name: Make user user1
  ansible.builtin.user:
    name: user1

- name: Make user user2
  ansible.builtin.user:
    name: user2

- name: Set authorized key for user1 without validating the TLS/SSL certificates
  ansible.posix.authorized_key:
    user: user1
    state: present
    key: https://github.com/---.keys
    validate_certs: False

- name: Set authorized key for user2 without validating the TLS/SSL certificates
  ansible.posix.authorized_key:
    user: user2   
    state: present
    key: https://github.com/---.keys
    validate_certs: False
